### ISSUE TITLE
[Feature Request]: Critical Notifications 

### ISSUE THREAD

**Issue by antunespa** [SgtBatten/HA_blueprints#212]
**Describe what you are trying to accomplish and why in non technical terms**
The critical notifications don't work in samsung galaxy phones.

**Describe the solution you'd like**
I like to receive critical notifications in my phone

**Additional context**
The only possibly to do that outside of your blueprint was with tts. Maybe you can introduce tts in your blueprint.

I tried the follow:

- alias: Send Voice Notification
    service: notify.mobile_app_a_s24ultra
    data:
      message: TTS
      data:
        ttl: 0
        priority: high
        media_stream: alarm_stream_max
        tts_text: Door Alarm

**Comment by SgtBatten** [comment]
Are you saying Samsung requires that media stream key?

**Comment by antunespa** [comment]
Yes and TTS, TSS is the only thing that do noise when smartphone are in vibrate mode or do not disturb.

**Comment by SgtBatten** [comment]
> Yes and TTS, TSS is the only thing that do noise when smartphone are in vibrate mode or do not disturb.

That is pretty annoying of samsung to overridde adnroid defaults like this.

**Comment by SgtBatten** [comment]
Could you see is #201 is the fix for this

**Comment by superdong69** [comment]
Man...I spent 2 hours today trying to figure WHERE this option had gone. I even spent an ADDITIONAL hour on the phone with Samsung support, they remoted into my machine, and was like...oh no, the option is gone since the new version, you'll have to wait until maybe an update fixes it. 
Unbelievable. Not sure if this will fix my notification issues, I'll test it over the coming days, but this link sure helped me a TON!

**Comment by SgtBatten** [comment]
TTS added in #221
